#ifndef _TIMERID_H_
#define _TIMERID_H_

enum _TIMERID_E_ {
	ISCROLL_TIMERID = 0x1124,
	ISUBAPP_TIMEID  = 0x1201,
	ISUBAPP_SSSS    = 0x1202,
	IINFO_LEAVE_TIMERID,
	IINFO_WAIT_TIMERID,
	ISEACH_TIMERID,
};

#endif//_TIMERID_H_
